name: Maven CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Java JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Cache Maven dependencies for faster builds
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Build the Maven project
      - name: Build with Maven
        run: mvn -B package

      # 5. Run unit tests
      - name: Run tests
        run: mvn test

      # 6. (Optional) Deploy to Azure WebApp
      # - name: Deploy to Azure WebApp
      #   uses: azure/webapps-deploy@v3
      #   with:
      #     app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #     package: target/*.war  # or target/*.jar depending on your project
